name: checkbox core snap daily build

on:
  workflow_dispatch:

jobs:
  snap:
    strategy:
      matrix:
        releases: [16, 18, 20, 22]
    runs-on: ubuntu-latest
    env:
      SERIES: series${{ matrix.releases }}
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
    name: Snap Checkbox Core snap for series ${{ matrix.releases }}

    steps:
      - uses: actions/checkout@v3
      - name: Copy over the common files for series ${{ matrix.releases }}
        run: |
          cd checkbox-core-snap/
          ./prepare.sh $SERIES
      - name: add LP credentials
        run: |
          mkdir -p ~/.local/share/snapcraft/provider/launchpad/
          echo '${{ secrets.LP_CREDS }}' > ~/.local/share/snapcraft/provider/launchpad/credentials
          git config --global user.email "ce-certifcation-qa@lists.canonical.com"
          git config --global user.name "Certification bot"
      - uses: snapcore/action-build@v1
        id: snapcraft
        with:
          path: checkbox-core-snap/series${{ matrix.releases }}
          snapcraft-channel: 7.x/stable
          snapcraft-args: remote-build --build-on amd64,arm64,armhf,i386 --launchpad-accept-public-upload
      - uses: actions/upload-artifact@v3
        with:
          name: series${{ matrix.releases }}
          path: checkbox-snap/series${{ matrix.releases }}/*.snap
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPCRAFT7_CREDS }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
