name: Metabox tests

on:
  workflow_dispatch:

jobs:
  Metabox:
    defaults:
      run:
        working-directory: metabox
    runs-on: ubuntu-latest
    env:
      PYCHARM_HOSTED: True
    steps:
      - name: Checkout checkbox monorepo
        uses: actions/checkout@v3
      - name: Setup LXD
        uses: canonical/setup-lxd@90d76101915da56a42a562ba766b1a77019242fd
      - name: Install tox
        run: pip install tox
      - name: Run tox
        run: tox
